[package]
name = "game-of-life"
version = "0.1.0"
authors = ["Daryl Pinto <daryl.j.pinto@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
